name: Send test report to Slack

inputs:
  webhook:
    type: string
    description: The Slack webhook URL to use
    required: true
  environment:
    type: string
    description: Environment tested
    required: true
  included-tests:
    type: string
    description: Included test tags
    required: false
    default: ""
  excluded-tests:
    type: string
    description: Excluded test tags
    required: false
    default: ""
  pass-count:
    type: string
    description: The number of passed tests
    required: true
  fail-count:
    type: string
    description: The number of failed tests
    required: true
  skip-count:
    type: string
    description: The number of skipped tests
    required: true
  flake-count:
    type: string
    description: The number of flaky tests
    required: true
  duration:
    type: string
    description: The number of seconds the test suite took to run
    required: true
  message-title:
    type: string
    description: The title of the Slack message
    required: false
    default: TNA Website Test Results
  description:
    type: string
    description: An optional description to add
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Create report summary
      id: report
      run: |
        touch report.txt
        echo "Environment: **${ENVIRONMENT}**" >> report.txt
        echo >> report.txt
        [[ -n "${INCLUDED_TESTS}" ]] && echo "- Included: \`${INCLUDED_TESTS}\`" >> report.txt
        [[ -n "${EXCLUDED_TESTS}" ]] && echo "- Excluded: \`${EXCLUDED_TESTS}\`" >> report.txt
        echo >> report.txt
        echo >> report.txt && echo "✅ **${PASS_COUNT}** tests passed" >> report.txt
        [[ "${FAIL_COUNT}" -gt 0 ]] && echo >> report.txt && echo "❌ **${FAIL_COUNT}** tests failed" >> report.txt
        [[ "${SKIP_COUNT}" -gt 0 ]] && echo >> report.txt && echo "🙈 **${SKIP_COUNT}** tests skipped" >> report.txt
        [[ "${FLAKE_COUNT}" -gt 0 ]] && echo >> report.txt && echo "🤕 **${FLAKE_COUNT}** flaky tests" >> report.txt
        TIME_TAKEN=$(date -u -d @"${DURATION}" +"%T")
        echo >> report.txt && echo "Time taken: **$TIME_TAKEN**" >> report.txt
        [[ -n "${DESCRIPTION}" ]] && echo >> report.txt && echo "${DESCRIPTION}" >> report.txt
        echo >> report.txt && echo "[Full report](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}) | [Source code](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/main/tests) | [WIP tests](${GITHUB_SERVER_URL}/search?q=repo%3A${GITHUB_REPOSITORY_OWNER}%2F${GITHUB_REPOSITORY}%20%28%40wip%29%20language%3ATypeScript&type=code&l=TypeScript)" >> report.txt
        cat report.txt
        {
          echo 'REPORT<<EOF'
          cat report.txt
          echo EOF
        } >> "$GITHUB_OUTPUT"
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        INCLUDED_TESTS: ${{ inputs.included-tests }}
        EXCLUDED_TESTS: ${{ inputs.excluded-tests }}
        PASS_COUNT: ${{ inputs.pass-count }}
        FAIL_COUNT: ${{ inputs.fail-count }}
        SKIP_COUNT: ${{ inputs.skip-count }}
        FLAKE_COUNT: ${{ inputs.flake-count }}
        DURATION: ${{ inputs.duration }}
        DESCRIPTION: ${{ inputs.description }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      shell: bash
    - uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
      env:
        SLACK_TITLE: ${{ inputs.message-title }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_ICON: https://raw.githubusercontent.com/nationalarchives/tna-frontend/main/src/nationalarchives/assets/images/apple-touch-icon.png
        SLACK_ICON_EMOJI: ":test_tube:"
        MSG_MINIMAL: true
        SLACK_COLOR: ${{ inputs.fail-count == '0' && 'good' || 'danger' }}
        ENABLE_ESCAPES: true
        SLACKIFY_MARKDOWN: true
        SLACK_MESSAGE: ${{ steps.report.outputs.REPORT }}
