name: Manual test run

on:
  workflow_dispatch:
    inputs:
      domain:
        type: string
        description: Domain to test
        required: true
        default: "https://www.nationalarchives.gov.uk/"
      include-tests:
        type: string
        description: Test tags to run, separated with a pipe "|" (leave blank to run all tests)
        required: false
        default: ""
      exclude-tests:
        type: string
        description: Test tags to exclude, separated with a pipe "|" (use @wip to exclude work in progress tests)
        required: false
        default: ""
      notify-slack-on-pass:
        type: boolean
        description: Send successful test results to Slack
        required: true
        default: true
      notify-slack-on-fail:
        type: boolean
        description: Send test failure results to Slack
        required: true
        default: true
      description:
        type: string
        description: A description to add to the Slack report
        required: false
        default: ""

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get test header value
        run: |
          if [[ "${{ inputs.domain }}" == *"dev-www.nationalarchives.gov.uk"* ]]; then
            echo "TEST_HEADER=${{ secrets.TEST_HEADER_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ inputs.domain }}" == *"staging-www.nationalarchives.gov.uk"* ]]; then
            echo "TEST_HEADER=${{ secrets.TEST_HEADER_STAGING }}" >> $GITHUB_ENV
          fi
      - name: Run tests
        id: playwright-tests
        uses: ./.github/actions/playwright-tests
        with:
          domain: ${{ inputs.domain }}
          include-tests: ${{ inputs.include-tests }}
          exclude-tests: ${{ inputs.exclude-tests }}
          test-header: ${{ env.TEST_HEADER }}
      - name: Send report to Slack
        if: (success() && inputs.notify-slack-on-pass) || (failure() && inputs.notify-slack-on-fail)
        uses: ./.github/actions/send-slack-report
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          domain: ${{ steps.playwright-tests.outputs.domain }}
          included-tests: ${{ inputs.include-tests }}
          excluded-tests: ${{ inputs.exclude-tests }}
          pass-count: ${{ steps.playwright-tests.outputs.pass-count }}
          fail-count: ${{ steps.playwright-tests.outputs.fail-count }}
          skip-count: ${{ steps.playwright-tests.outputs.skip-count }}
          flake-count: ${{ steps.playwright-tests.outputs.flake-count }}
          duration: ${{ steps.playwright-tests.outputs.duration }}
          description: ${{ inputs.description }}
