name: Nightly production smoke tests

on:
  # schedule:
  #   - cron: "0 4 * * 2-5"  # 04:00 Tue-Fri
  workflow_dispatch:

env:
  DOMAIN: https://www.nationalarchives.gov.uk
  INCLUDE_TESTS: "@smoke"
  EXCLUDE_TESTS: "@wip"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: playwright-tests
        uses: ./.github/actions/playwright-tests
        with:
          domain: ${{ env.DOMAIN }}
          include-tests: ${{ env.INCLUDE_TESTS }}
          exclude-tests: ${{ env.EXCLUDE_TESTS }}
      - name: Send report to Slack
        if: '!cancelled()'
        uses: ./.github/actions/send-slack-report
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          domain: ${{ steps.playwright-tests.outputs.domain }}
          included-tests: ${{ env.INCLUDE_TESTS }}
          excluded-tests: ${{ env.EXCLUDE_TESTS }}
          pass-count: ${{ steps.playwright-tests.outputs.pass-count }}
          fail-count: ${{ steps.playwright-tests.outputs.fail-count }}
          skip-count: ${{ steps.playwright-tests.outputs.skip-count }}
          flake-count: ${{ steps.playwright-tests.outputs.flake-count }}
          duration: ${{ steps.playwright-tests.outputs.duration }}
          message-title: TNA Website Nightly Smoke Test Results
