name: Run tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to test
        options:
          - production
          - staging
          - develop
        default: "develop"
      include-tests:
        type: string
        description: Test tags to run, separated with a pipe "|" (leave blank to run all tests)
        required: false
        default: ""
      exclude-tests:
        type: string
        description: Test tags to exclude, separated with a pipe "|" (@wip is already excluded)
        required: false
        default: ""
      notify-slack-on-pass:
        type: boolean
        description: Send successful test results to Slack
        required: true
        default: true
      notify-slack-on-fail:
        type: boolean
        description: Send test failure results to Slack
        required: true
        default: true
      description:
        type: string
        description: A description to add to the Slack report
        required: false
        default: ""

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          sudo apt-get update
          apt-get install -y libnss3 libatk-bridge2.0-0 libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1
          npm install
          npx playwright install
      - name: Get header value
        run: |
          if [[ "${{ inputs.environment }}" == "develop" ]]; then
            echo "TEST_ACCESS_HEADER=${{ secrets.TEST_HEADER_DEV }}" >> $GITHUB_ENV
            echo "TEST_WAGTAIL_API_TOKEN=${{ secrets.TEST_WAGTAIL_API_TOKEN_DEV }}" >> $GITHUB_ENV
          elif [[ "${{ inputs.environment }}" == "staging" ]]; then
            echo "TEST_ACCESS_HEADER=${{ secrets.TEST_HEADER_STAGING }}" >> $GITHUB_ENV
            echo "TEST_WAGTAIL_API_TOKEN=${{ secrets.TEST_WAGTAIL_API_TOKEN_STAGING }}" >> $GITHUB_ENV
          else
            echo "TEST_ACCESS_HEADER=${{ secrets.TEST_HEADER_PROD }}" >> $GITHUB_ENV
            echo "TEST_WAGTAIL_API_TOKEN=${{ secrets.TEST_WAGTAIL_API_TOKEN_PROD }}" >> $GITHUB_ENV
          fi
      - name: Show test configuration
        run: |
          echo "Environment: ${ENVIRONMENT}" >> $GITHUB_STEP_SUMMARY
          echo "Include: ${INCLUDED_TESTS}" >> $GITHUB_STEP_SUMMARY
          echo "Exclude: ${EXCLUDED_TESTS}" >> $GITHUB_STEP_SUMMARY
          echo "Description: ${DESCRIPTION}" >> $GITHUB_STEP_SUMMARY
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          INCLUDED_TESTS: ${{ inputs.include-tests }}
          EXCLUDED_TESTS: ${{ inputs.exclude-tests }}
          DESCRIPTION: ${{ inputs.description }}
      - name: Run tests
        run: ENVIRONMENT="${ENVIRONMENT}" TEST_ACCESS_HEADER="${TEST_ACCESS_HEADER}" TEST_WAGTAIL_API_TOKEN="${TEST_WAGTAIL_API_TOKEN}" CI=true npx playwright test --grep "${INCLUDED_TESTS}" --grep-invert "${EXCLUDED_TESTS}${{ env.EXCLUDED_TESTS && '|'}}@wip"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          INCLUDED_TESTS: ${{ inputs.include-tests }}
          EXCLUDED_TESTS: ${{ inputs.exclude-tests }}
      - name: Report summary
        if: always()
        run: |
          echo "PASS_COUNT=$(jq '(.stats.expected)' test-results.json)" >> "$GITHUB_ENV"
          echo "FAIL_COUNT=$(jq '(.stats.unexpected)' test-results.json)" >> "$GITHUB_ENV"
          echo "SKIP_COUNT=$(jq '(.stats.skipped)' test-results.json)" >> "$GITHUB_ENV"
          echo "FLAKE_COUNT=$(jq '(.stats.flaky)' test-results.json)" >> "$GITHUB_ENV"
          echo "DURATION=$(jq '(.stats.duration/1000|tonumber|floor)' test-results.json)" >> "$GITHUB_ENV"
      - name: Send report to Slack
        if: (success() && inputs.notify-slack-on-pass) || (failure() && inputs.notify-slack-on-fail)
        uses: ./.github/actions/send-slack-report
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK }}
          environment: ${{ env.ENVIRONMENT }}
          included-tests: ${{ env.INCLUDED_TESTS }}
          excluded-tests: ${{ env.EXCLUDED_TESTS }}
          pass-count: ${{ env.PASS_COUNT }}
          fail-count: ${{ env.FAIL_COUNT }}
          skip-count: ${{ env.SKIP_COUNT }}
          flake-count: ${{ env.FLAKE_COUNT }}
          duration: ${{ env.DURATION }}
          description: ${{ env.DESCRIPTION }}
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          INCLUDED_TESTS: ${{ inputs.include-tests }}
          EXCLUDED_TESTS: ${{ inputs.exclude-tests }}
          DESCRIPTION: ${{ inputs.description }}
