name: Test Slack

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Initiate the deployment launch sequence
        id: launch_sequence
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployment started :eyes:"
            attachments:
              - color: "dbab09"
              fields:
                - title: "Status"
                short: true
                value: "In Progress"
    outputs:
      ts: ${{ steps.launch_sequence.outputs.ts }}

  complete:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Countdown until launch
        run: sleep 10
      - name: Update the original message with success
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.update
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            ts: "${{ needs.prepare.outputs.ts }}"
            text: "Deployment finished! :rocket:"
            attachments:
              - color: "28a745"
              fields:
                - title: "Status"
                short: true
                value: "Completed"
